name = "github-webhook-proxy"
main = "src/worker.ts"
compatibility_date = "2024-09-02"

workers_dev = false
send_metrics = false

[[kv_namespaces]]
binding = "WEBHOOK_SECRETS"
id = "9f64095cc2fc4e81a2ca6ef5f66d768e"
