name = "github-webhook-proxy"
main = "src/worker.ts"
compatibility_date = "2023-10-10"

workers_dev = false
send_metrics = false

[[kv_namespaces]]
binding = "WEBHOOK_SECRETS"
id = "9f64095cc2fc4e81a2ca6ef5f66d768e"
preview_id = "c1bbbcd86efe4d91a5b3391a5b862a86"
